name: Manifest Interactive - Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Production
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Trigger Deployment
        run: /usr/local/bin/deploy-production
