name: Manifest Interactive - Staging
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy to Staging
    runs-on: [self-hosted, Linux, X64]
    needs: [build_and_test]
    steps:
      - name: Trigger Deployment
        run: /usr/local/bin/deploy-development
